maintainer: syuilo <i@syuilo.com>
host: misskey.local
port: 80
bindPort: 80
https:
  enable: false
  key: null
  cert: null
sessionSecret: 'Himasaku#06160907'
recaptcha:
  siteKey: 6LdtwxUTAAAAAJlGBV9_fxy-szKJ-3hCscF3md76
  secretKey: 6LdtwxUTAAAAAHOcFtsjHZn0Cj-OILDyB1xA9rWc
api:
  key: 'himasaku#06160907'
  host: api.misskey.local
  port: 616
  secure: false
mongodb:
  host: localhost
  port: 27017
  db: misskey-web
  user: syuilo
  pass: Syuilo8901
redis:
  host: localhost
  port: 6379
  pass: ''
